#pragma once
#include "stdafx.h"
#include <iostream>
#include <opencv2\core.hpp>
#include "opencv2\features2d\features2d.hpp"
#include <opencv2\features2d.hpp>
#include <opencv2\highgui\highgui.hpp>
#include <opencv2\imgproc\imgproc.hpp>
#include "opencv2\videoio.hpp"
#include "opencv2\imgcodecs.hpp"
#include "opencv2\imgproc.hpp"
#include <Windows.h>
#include <shlobj.h>
#include <cstdio>
#include <iostream>
#include <map>
#include <stack>
#include <tchar.h>
#include <windows.h>

